repos:
  - repo: local
    hooks:
      - id: block-quick-secret-patterns
        name: Block quick secret patterns (python)
        entry: python scripts/hooks/pre_commit_check.py
        language: python
        types: [text]
        stages: [pre-commit]
