repos:
  - repo: local
    hooks:
      - id: block-quick-secret-patterns
        name: Block quick secret patterns (node)
        entry: node scripts/hooks/pre_commit_check.cjs
        language: node
        types: [text]
        stages: [pre-commit]
