version: '3.8'

services:
  # Neo4j Database for Knowledge Graph Storage
  neo4j:
    image: neo4j:5.26.0
    container_name: trading-agents-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - trading-agents
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  # Zep Graphiti Memory Service
  zep-graphiti:
    image: zepai/graphiti:latest
    container_name: trading-agents-zep-graphiti
    ports:
      - "8000:8000"
    environment:
      NEO4J_URI: bolt://trading-agents-neo4j:7687
      NEO4J_USER: ${NEO4J_USER:-neo4j}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
    env_file:
      - py_zep/.env.local
    volumes:
      - ./py_zep/secrets/enhanced-init.py:/init.py:ro
      - ./py_zep/graph_service/zep_graphiti.py:/app/graph_service/zep_graphiti.py:ro
      - ./py_zep/secrets/start-wrapper.sh:/start-wrapper.sh:ro
    command: ["/bin/sh", "/start-wrapper.sh", "python3", "/init.py"]
    secrets:
      - openai_api_key
      - embedder_api_key
      - neo4j_user
      - neo4j_password
      - lm_studio_url
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - trading-agents
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/docs || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  # Reddit Sentiment Analysis Service (FEATURE-FLAGGED)
  reddit-service:
    profiles: ["reddit"]  # Only starts when --profile reddit is used
    build:
      context: ./services/reddit-service
      dockerfile: Dockerfile
    image: reddit-service:latest
    container_name: trading-reddit-service
    restart: unless-stopped

    environment:
      - NODE_ENV=production
      - PORT=3001
      - LOG_LEVEL=info

    # Environment file for Reddit API credentials
    env_file:
      - ./services/reddit-service/.env.local

    ports:
      - "3001:3001"

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3001/health').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Security settings
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /app/reddit-service.log:rw,noexec,nosuid,size=50m

    # Network isolation
    networks:
      - reddit-network
      - trading-agents

  # Main Trading Agents Application
  trading-agents:
    build:
      context: ./js
      dockerfile: Dockerfile
      target: production
    image: trading-agents:latest
    container_name: trading-agents-cli
    restart: unless-stopped

    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - REDDIT_SERVICE_URL=http://reddit-service:3001
      - ZEP_GRAPHITI_URL=http://zep-graphiti:8000
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}

    env_file:
      - ./js/.env.local

    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
      - ./js/config:/app/config:ro

    depends_on:
      neo4j:
        condition: service_healthy
      zep-graphiti:
        condition: service_started
      # reddit-service dependency removed - will only be included when --profile reddit is used

    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

    networks:
      - trading-agents

networks:
  # Internal network for Reddit service (only created when reddit profile is active)
  reddit-network:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.21.0.0/16

  # Main trading network with external access
  trading-agents:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  # Neo4j data persistence
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local

  # Trading agents data persistence
  trading-data:
    driver: local
  trading-logs:
    driver: local

secrets:
  openai_api_key:
    file: ./py_zep/secrets/openai_api_key.txt
  embedder_api_key:
    file: ./py_zep/secrets/embedder_api_key.txt
  neo4j_user:
    file: ./py_zep/secrets/neo4j_user.txt
  neo4j_password:
    file: ./py_zep/secrets/neo4j_password.txt
  lm_studio_url:
    file: ./py_zep/secrets/lm_studio_url.txt