# Development overrides for docker-compose.yml
# Automatically applied when running docker-compose commands

services:
  # Development configuration for services
  redis:
    environment:
      - REDIS_PASSWORD=  # No password for development
    
  neo4j:
    environment:
      - NEO4J_AUTH=neo4j/development
      
  trading-agents:
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - ./services/trading-agents/src:/app/src:ro
      
  web-api:
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      
  web-frontend:
    environment:
      - NODE_ENV=development