version: '3.8'

services:
  # Reddit Sentiment Analysis Service
  reddit-service:
    build:
      context: ./services/reddit-service
      dockerfile: Dockerfile
    image: reddit-service:latest
    container_name: trading-reddit-service
    restart: unless-stopped
    
    environment:
      - NODE_ENV=production
      - PORT=3001
      - LOG_LEVEL=info
      
    # Environment file for Reddit API credentials
    env_file:
      - ./services/reddit-service/.env
    
    ports:
      - "3001:3001"
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3001/health').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /app/reddit-service.log:rw,noexec,nosuid,size=50m
    
    # Network isolation
    networks:
      - reddit-network
      - trading-network

  # Main Trading Agents Service
  trading-agents:
    build:
      context: ./js
      dockerfile: Dockerfile
      target: production
    image: trading-agents:latest
    container_name: trading-agents-cli
    restart: unless-stopped
    
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - REDDIT_SERVICE_URL=http://reddit-service:3001
      
    env_file:
      - .env
    
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
      - ./config:/app/config:ro
    
    depends_on:
      reddit-service:
        condition: service_healthy
    
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    
    networks:
      - trading-network

networks:
  # Internal network for Reddit service
  reddit-network:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.21.0.0/16
  
  # Main trading network with external access
  trading-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  trading-data:
    driver: local
  trading-logs:
    driver: local