/**
 * Base Trading Strategy Interface and Abstract Classes
 * 
 * This module defines the foundational interfaces and abstract classes for all trading strategies.
 * It provides a standardized framework for strategy development, backtesting, and execution.
 * 
 * TODO: Add strategy performance tracking and analytics
 * TODO: Implement strategy optimization and parameter tuning
 * TODO: Add multi-asset and portfolio-level strategies
 */

import { TradingAgentsConfig } from '../config';

/**
 * Signal types for trading decisions
 */
export enum SignalType {
  BUY = 'BUY',
  SELL = 'SELL',
  HOLD = 'HOLD',
  STRONG_BUY = 'STRONG_BUY',
  STRONG_SELL = 'STRONG_SELL'
}

/**
 * Signal strength levels
 */
export enum SignalStrength {
  VERY_WEAK = 1,
  WEAK = 2,
  MODERATE = 3,
  STRONG = 4,
  VERY_STRONG = 5
}

/**
 * Risk level classifications
 */
export enum RiskLevel {
  VERY_LOW = 'VERY_LOW',
  LOW = 'LOW',
  MODERATE = 'MODERATE',
  HIGH = 'HIGH',
  VERY_HIGH = 'VERY_HIGH'
}

/**
 * Market data point interface
 */
export interface MarketData {
  symbol: string;
  timestamp: Date;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  technicalIndicators?: Record<string, any>;
}

/**
 * Trading signal generated by strategies
 */
export interface TradingSignal {
  symbol: string;
  signal: SignalType;
  strength: SignalStrength;
  confidence: number; // 0-100
  timestamp: Date;
  price: number;
  reasoning: string;
  riskLevel: RiskLevel;
  stopLoss?: number;
  takeProfit?: number;
  positionSize?: number;
  metadata?: Record<string, any>;
}

/**
 * Strategy configuration parameters
 */
export interface StrategyConfig {
  name: string;
  enabled: boolean;
  parameters: Record<string, any>;
  riskTolerance: RiskLevel;
  maxPositionSize: number;
  stopLossPercent: number;
  takeProfitPercent: number;
  lookbackPeriod: number;
}

/**
 * Strategy performance metrics
 */
export interface StrategyPerformance {
  totalTrades: number;
  winningTrades: number;
  losingTrades: number;
  winRate: number;
  totalReturn: number;
  maxDrawdown: number;
  sharpeRatio: number;
  sortino: number;
  averageWin: number;
  averageLoss: number;
  profitFactor: number;
  lastUpdated: Date;
}

/**
 * Base interface for all trading strategies
 */
export interface ITradingStrategy {
  readonly name: string;
  readonly description: string;
  readonly config: StrategyConfig;
  
  /**
   * Analyze market data and generate trading signals
   */
  analyze(marketData: MarketData[], currentPosition?: number): Promise<TradingSignal[]>;
  
  /**
   * Validate strategy configuration and parameters
   */
  validate(): boolean;
  
  /**
   * Get strategy performance metrics
   */
  getPerformance(): StrategyPerformance;
  
  /**
   * Update strategy configuration
   */
  updateConfig(newConfig: Partial<StrategyConfig>): void;
  
  /**
   * Check if strategy should be active based on market conditions
   */
  shouldActivate(marketConditions: Record<string, any>): boolean;
}

/**
 * Abstract base class for trading strategies
 * 
 * TODO: Add strategy state management and persistence
 * TODO: Implement strategy lifecycle hooks (onStart, onStop, onReset)
 * TODO: Add strategy debugging and logging capabilities
 */
export abstract class BaseTradingStrategy implements ITradingStrategy {
  protected readonly tradingConfig: TradingAgentsConfig;
  protected performance: StrategyPerformance;
  protected signalHistory: TradingSignal[];
  
  constructor(
    public readonly name: string,
    public readonly description: string,
    public config: StrategyConfig,
    tradingConfig: TradingAgentsConfig
  ) {
    this.tradingConfig = tradingConfig;
    this.signalHistory = [];
    this.performance = this.initializePerformance();
  }

  /**
   * Initialize performance tracking
   */
  private initializePerformance(): StrategyPerformance {
    return {
      totalTrades: 0,
      winningTrades: 0,
      losingTrades: 0,
      winRate: 0,
      totalReturn: 0,
      maxDrawdown: 0,
      sharpeRatio: 0,
      sortino: 0,
      averageWin: 0,
      averageLoss: 0,
      profitFactor: 0,
      lastUpdated: new Date()
    };
  }

  /**
   * Abstract method for market analysis - must be implemented by subclasses
   */
  abstract analyze(marketData: MarketData[], currentPosition?: number): Promise<TradingSignal[]>;

  /**
   * Validate strategy configuration
   * 
   * TODO: Add comprehensive parameter validation
   * TODO: Implement dynamic validation based on strategy type
   */
  validate(): boolean {
    try {
      // Basic validation
      if (!this.config.name || this.config.name.trim() === '') {
        console.error(`${this.name}: Strategy name is required`);
        return false;
      }

      if (this.config.maxPositionSize <= 0 || this.config.maxPositionSize > 1) {
        console.error(`${this.name}: Invalid max position size. Must be between 0 and 1`);
        return false;
      }

      if (this.config.lookbackPeriod <= 0) {
        console.error(`${this.name}: Lookback period must be positive`);
        return false;
      }

      // TODO: Add strategy-specific validation
      return this.validateStrategySpecific();

    } catch (error) {
      console.error(`${this.name}: Validation error:`, error);
      return false;
    }
  }

  /**
   * Strategy-specific validation - override in subclasses
   */
  protected validateStrategySpecific(): boolean {
    return true;
  }

  /**
   * Get current performance metrics
   */
  getPerformance(): StrategyPerformance {
    return { ...this.performance };
  }

  /**
   * Update strategy configuration
   * 
   * TODO: Add configuration change validation
   * TODO: Implement hot-swapping of parameters
   */
  updateConfig(newConfig: Partial<StrategyConfig>): void {
    this.config = { ...this.config, ...newConfig };
    
    // Re-validate after config update
    if (!this.validate()) {
      console.warn(`${this.name}: Configuration update resulted in invalid state`);
    }
  }

  /**
   * Default activation logic - can be overridden
   * 
   * TODO: Implement sophisticated market regime detection
   * TODO: Add strategy ensemble coordination
   */
  shouldActivate(marketConditions: Record<string, any>): boolean {
    if (!this.config.enabled) {
      return false;
    }

    // TODO: Add market condition analysis
    // For now, simple activation based on volatility
    const volatility = marketConditions.volatility || 0;
    const maxVolatility = this.config.parameters.maxVolatility || 0.05;
    
    return volatility <= maxVolatility;
  }

  /**
   * Helper method to create trading signals
   * 
   * TODO: Add signal validation and quality scoring
   * TODO: Implement signal aggregation and filtering
   */
  protected createSignal(
    symbol: string,
    signalType: SignalType,
    strength: SignalStrength,
    confidence: number,
    price: number,
    reasoning: string,
    metadata?: Record<string, any>
  ): TradingSignal {
    const signal: TradingSignal = {
      symbol,
      signal: signalType,
      strength,
      confidence: Math.max(0, Math.min(100, confidence)),
      timestamp: new Date(),
      price,
      reasoning,
      riskLevel: this.calculateRiskLevel(strength, confidence),
      metadata: metadata || {}
    };

    // Add risk management parameters
    if (signalType === SignalType.BUY || signalType === SignalType.STRONG_BUY) {
      signal.stopLoss = price * (1 - this.config.stopLossPercent / 100);
      signal.takeProfit = price * (1 + this.config.takeProfitPercent / 100);
    } else if (signalType === SignalType.SELL || signalType === SignalType.STRONG_SELL) {
      signal.stopLoss = price * (1 + this.config.stopLossPercent / 100);
      signal.takeProfit = price * (1 - this.config.takeProfitPercent / 100);
    }

    // Calculate position size based on risk
    signal.positionSize = this.calculatePositionSize(signal);

    // Store signal for performance tracking
    this.signalHistory.push(signal);

    return signal;
  }

  /**
   * Calculate risk level based on signal characteristics
   * 
   * TODO: Implement sophisticated risk scoring
   * TODO: Add market volatility considerations
   */
  protected calculateRiskLevel(strength: SignalStrength, confidence: number): RiskLevel {
    const riskScore = (strength * 20) + confidence;
    
    if (riskScore >= 400) return RiskLevel.VERY_LOW;
    if (riskScore >= 300) return RiskLevel.LOW;
    if (riskScore >= 200) return RiskLevel.MODERATE;
    if (riskScore >= 100) return RiskLevel.HIGH;
    return RiskLevel.VERY_HIGH;
  }

  /**
   * Calculate position size based on signal risk and strategy config
   * 
   * TODO: Implement Kelly Criterion and other position sizing methods
   * TODO: Add portfolio correlation considerations
   */
  protected calculatePositionSize(signal: TradingSignal): number {
    const baseSize = this.config.maxPositionSize;
    const riskMultiplier = this.getRiskMultiplier(signal.riskLevel);
    const confidenceMultiplier = signal.confidence / 100;
    
    return Math.min(baseSize, baseSize * riskMultiplier * confidenceMultiplier);
  }

  /**
   * Get risk multiplier for position sizing
   */
  private getRiskMultiplier(riskLevel: RiskLevel): number {
    switch (riskLevel) {
      case RiskLevel.VERY_LOW: return 1.0;
      case RiskLevel.LOW: return 0.8;
      case RiskLevel.MODERATE: return 0.6;
      case RiskLevel.HIGH: return 0.4;
      case RiskLevel.VERY_HIGH: return 0.2;
      default: return 0.5;
    }
  }

  /**
   * Update performance metrics after trade execution
   * 
   * TODO: Implement real-time performance tracking
   * TODO: Add benchmark comparison and attribution analysis
   */
  protected updatePerformance(trade: { profit: number; duration: number }): void {
    this.performance.totalTrades++;
    
    if (trade.profit > 0) {
      this.performance.winningTrades++;
      // TODO: Update average win calculation
    } else {
      this.performance.losingTrades++;
      // TODO: Update average loss calculation
    }

    this.performance.winRate = this.performance.winningTrades / this.performance.totalTrades;
    this.performance.totalReturn += trade.profit;
    this.performance.lastUpdated = new Date();

    // TODO: Calculate drawdown, Sharpe ratio, etc.
  }
}

/**
 * Strategy factory for creating strategy instances
 * 
 * TODO: Add dynamic strategy loading from configuration
 * TODO: Implement strategy plugin system
 */
export class StrategyFactory {
  private static strategies: Map<string, new (...args: any[]) => ITradingStrategy> = new Map();

  /**
   * Register a strategy class
   */
  static register(name: string, strategyClass: new (...args: any[]) => ITradingStrategy): void {
    this.strategies.set(name, strategyClass);
  }

  /**
   * Create strategy instance by name
   */
  static create(name: string, config: StrategyConfig, ...args: any[]): ITradingStrategy | null {
    const StrategyClass = this.strategies.get(name);
    if (!StrategyClass) {
      console.error(`Strategy '${name}' not found in factory`);
      return null;
    }

    try {
      return new StrategyClass(config, ...args);
    } catch (error) {
      console.error(`Error creating strategy '${name}':`, error);
      return null;
    }
  }

  /**
   * Get list of available strategies
   */
  static getAvailableStrategies(): string[] {
    return Array.from(this.strategies.keys());
  }
}