services:
  neo4j:
    image: neo4j:5.26.0
    container_name: trading-agents-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - trading_agents
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  zep-graphiti:
    image: zepai/graphiti:latest
    container_name: trading-agents-zep-graphiti
    ports:
      - "8000:8000"
    environment:
      NEO4J_URI: bolt://trading-agents-neo4j:7687
      NEO4J_USER: ${NEO4J_USER:-neo4j}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
    env_file:
      - .env.local
    volumes:
      - ./secrets/enhanced-init.py:/init.py:ro
      - ./graph_service/zep_graphiti.py:/app/graph_service/zep_graphiti.py:ro
      - ./secrets/start-wrapper.sh:/start-wrapper.sh:ro
    command: ["/bin/sh", "/start-wrapper.sh", "python3", "/init.py"]
    # Keep secrets as fallback for production deployments
    secrets:
      - openai_api_key
      - embedder_api_key
      - neo4j_user
      - neo4j_password
      - lm_studio_url
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - trading_agents
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/docs || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  trading_agents: {}

secrets:
  openai_api_key:
    file: ./secrets/openai_api_key.txt
  embedder_api_key:
    file: ./secrets/embedder_api_key.txt
  neo4j_user:
    file: ./secrets/neo4j_user.txt
  neo4j_password:
    file: ./secrets/neo4j_password.txt
  lm_studio_url:
    file: ./secrets/lm_studio_url.txt
  marketstack_api_key:
    file: ./secrets/marketstack_api_key.txt
  reddit_client_id:
    file: ./secrets/reddit_client_id.txt
  reddit_client_secret:
    file: ./secrets/reddit_client_secret.txt
  reddit_refresh_token:
    file: ./secrets/reddit_refresh_token.txt
  reddit_username:
    file: ./secrets/reddit_username.txt
  reddit_password:
    file: ./secrets/reddit_password.txt
