version: '3.8'

services:
  trading-agents:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: trading-agents:latest
    container_name: trading-agents-cli
    restart: unless-stopped
    
    # Environment variables
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      
    # Environment file for API keys (create .env file)
    env_file:
      - .env
    
    # Volumes for persistent data
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
      - ./config:/app/config:ro
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    
    # Network
    networks:
      - trading-network

  # Optional: Add monitoring container
  # monitoring:
  #   image: prom/node-exporter:latest
  #   container_name: trading-monitoring
  #   ports:
  #     - "9100:9100"
  #   networks:
  #     - trading-network

networks:
  trading-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  trading-data:
    driver: local
  trading-logs:
    driver: local