name: gitleaks scan

on:
  pull_request:
  schedule:
    - cron: '0 3 * * *'

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: '--path=. --report-format=json --report-path=./gitleaks-report.json'
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
