name: Secret Scan (Gitleaks + Heuristic)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gitleaks:
    name: Run Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          fail: true
      - name: Heuristic repo secret scan (threshold 0)
        shell: pwsh
        env:
          SECRET_SCAN_FAIL_ON_MATCH: 'true'
          SECRET_SCAN_MAX_MATCHES: '0'
          SECRET_SCAN_VERBOSE: 'true'
        run: |
          pwsh -NoLogo -NoProfile -ExecutionPolicy Bypass -File tools/secret-scan.ps1
      - name: Upload heuristic scan artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: secret-scan-results
          path: |
            secrets-scan-results.json
            secrets-scan-results.txt